package com.tosspaper.aiengine.service.impl;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.tosspaper.aiengine.agent.ComparisonEvent;
import com.tosspaper.aiengine.agent.StreamingComparisonAgent;
import com.tosspaper.aiengine.repository.DocumentPartComparisonRepository;
import com.tosspaper.aiengine.repository.ExtractionTaskRepository;
import com.tosspaper.models.domain.ComparisonContext;
import com.tosspaper.models.domain.ExtractionTask;
import com.tosspaper.models.domain.PurchaseOrder;
import com.tosspaper.models.exception.BadRequestException;
import com.tosspaper.models.extraction.dto.Comparison;
import com.tosspaper.models.service.PurchaseOrderLookupService;
import io.micrometer.observation.annotation.Observed;
import lombok.extern.slf4j.Slf4j;
import org.jooq.DSLContext;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;

/**
 * Streaming implementation of DocumentPartComparisonService.
 * Uses ChatClient with embedded Java tools instead of CLI-based agent.
 *
 * <p>Activated when {@code ai.comparison.streaming.enabled=true}.
 *
 * <p>Benefits over CLI-based implementation:
 * <ul>
 *   <li>~1MB per request vs ~500MB for Node.js CLI process</li>
 *   <li>100+ concurrent requests per 4GB instance (vs 2-3)</li>
 *   <li>Real-time SSE streaming of progress</li>
 *   <li>Embedded file tools (no process spawn overhead)</li>
 *   <li>Multi-provider support (OpenAI, Anthropic)</li>
 * </ul>
 *
 * <p>Provides:
 * <ul>
 *   <li>{@link #executeComparisonStreamAndSave(ComparisonContext)} - Streaming for SSE with DB persistence</li>
 *   <li>{@link #compareDocumentParts(ComparisonContext)} - Blocking for backend (caller saves in transaction)</li>
 * </ul>
 */
@Slf4j
@Service
@Primary
@ConditionalOnProperty(name = "ai.comparison.streaming.enabled", havingValue = "true")
public class StreamingDocumentComparisonService extends AbstractDocumentPartComparisonService {

    private final StreamingComparisonAgent streamingAgent;

    public StreamingDocumentComparisonService(
            ObjectMapper objectMapper,
            DocumentPartComparisonRepository repository,
            ExtractionTaskRepository extractionTaskRepository,
            DSLContext dslContext,
            StreamingComparisonAgent streamingAgent,
            PurchaseOrderLookupService poService) {
        super(objectMapper, repository, extractionTaskRepository, dslContext, poService);
        this.streamingAgent = streamingAgent;
        log.info("StreamingDocumentComparisonService initialized - using ChatClient with embedded tools");
    }

    /**
     * Execute document comparison with streaming events.
     * Does NOT save the result - caller is responsible for persistence.
     * Use this when you need to save within your own transaction (e.g., ExtractionService).
     *
     * @param context Comparison context containing PO and extraction task
     * @return Flux of ComparisonEvents for real-time progress updates
     */
    public Flux<ComparisonEvent> executeComparisonStream(ComparisonContext context) {
        ExtractionTask task = context.extractionTask();

        log.info("Starting streaming comparison: companyId={}, extractionId={}, poNumber={}",
                task.getCompanyId(), task.getAssignedId(), task.getPoNumber());

        return streamingAgent.executeComparison(context)
                .doOnComplete(() -> log.info("Streaming comparison completed: extractionId={}",
                        task.getAssignedId()))
                .doOnError(error -> log.error("Streaming comparison failed: extractionId={}",
                        task.getAssignedId(), error));
    }

    /**
     * Trigger a comparison for a document with streaming events.
     * Validates the extraction task, looks up PO, runs comparison, and saves result.
     * Use this for API endpoints that need SSE streaming.
     *
     * @param assignedId Extraction task assigned ID
     * @param companyId Company ID for authorization
     * @param comparisonId Unique session ID for isolation (generated by controller)
     * @return Flux of ComparisonEvents for real-time progress updates
     * @throws BadRequestException if validation fails
     */
    public Flux<ComparisonEvent> triggerComparisonStream(String assignedId, Long companyId, String comparisonId) {
        log.info("Triggering streaming comparison: assignedId={}, companyId={}, comparisonId={}",
                assignedId, companyId, comparisonId);

        // 1. Fetch and validate extraction task
        ExtractionTask task = extractionTaskRepository.findByAssignedId(assignedId);

        if (task == null) {
            log.warn("Extraction task not found: {}", assignedId);
            throw new BadRequestException("EXTRACTION_NOT_FOUND", "Extraction task not found: " + assignedId);
        }

        if (!task.getCompanyId().equals(companyId)) {
            log.warn("Company mismatch for task: {} (expected={}, actual={})",
                    assignedId, companyId, task.getCompanyId());
            throw new BadRequestException("COMPANY_MISMATCH", "Company ID mismatch for extraction task");
        }

        if (task.getPurchaseOrderId() == null || task.getPurchaseOrderId().isBlank()) {
            log.warn("No PO linked for task: {}", assignedId);
            throw new BadRequestException("NO_PO_LINKED", "No purchase order linked to this document");
        }

        if (task.getConformedJson() == null || task.getConformedJson().isBlank()) {
            log.warn("Document not conformed: {}", assignedId);
            throw new BadRequestException("NOT_CONFORMED", "Document has not been conformed yet");
        }

        // 2. Look up PO
        PurchaseOrder po = poLookupService.getPoWithItemsByPoNumber(companyId, task.getPoNumber())
                .orElseThrow(() -> {
                    log.error("PO not found for task: {}", assignedId);
                    return new BadRequestException("PO_NOT_FOUND", "Purchase order not found");
                });

        // 3. Run comparison with streaming and save (comparisonId provides session isolation)
        ComparisonContext context = new ComparisonContext(po, task, comparisonId);
        return executeComparisonStreamAndSave(context);
    }

    /**
     * Execute document comparison with streaming events AND save to database.
     * Emits a "Saving result..." activity event before persisting.
     *
     * @param context Comparison context containing PO and extraction task
     * @return Flux of ComparisonEvents for real-time progress updates
     */
    private Flux<ComparisonEvent> executeComparisonStreamAndSave(ComparisonContext context) {
        ExtractionTask task = context.extractionTask();

        return executeComparisonStream(context)
                .doOnNext(event -> log.debug("Event received in concatMap: {}", event.eventType()))
                .concatMap(event -> {
                    // When complete, emit saving activity, save to DB, then emit complete
                    if (event instanceof ComparisonEvent.Complete complete) {
                        log.info("Complete event received, saving comparison for: {}", task.getAssignedId());
                        ComparisonEvent savingActivity = new ComparisonEvent.Activity("💾", "Saving result...");
                        return Flux.just(savingActivity)
                                .doOnNext(ignored -> saveComparison(task.getAssignedId(), complete.result()))
                                .concatWith(Flux.just(event));
                    }
                    return Flux.just(event);
                });
    }

    private void saveComparison(String assignedId, Comparison comparison) {
        try {
            dslContext.transaction(ctx -> {
                repository.upsert(ctx.dsl(), assignedId, comparison);
                log.info("Saved comparison result for assignedId: {}", assignedId);
            });
        } catch (Exception e) {
            log.error("Failed to save comparison for assignedId: {}", assignedId, e);
        }
    }

    /**
     * Blocking implementation for backend calls (e.g., ExtractionService).
     * Does NOT save the result - caller is responsible for persistence.
     *
     * @param context Comparison context containing PO and extraction task
     * @return Comparison result
     */
    @Override
    @Observed(
            name = "document.part.comparison.streaming",
            contextualName = "Compare Document Parts (Streaming)",
            lowCardinalityKeyValues = {"service", "comparison", "operation", "compare-parts-streaming"}
    )
    public Comparison compareDocumentParts(ComparisonContext context) {
        ExtractionTask task = context.extractionTask();

        log.info("Starting blocking comparison: companyId={}, extractionId={}",
                task.getCompanyId(), task.getAssignedId());

        return streamingAgent.executeComparisonBlocking(context);
    }
}
