package com.tosspaper.precon

import com.tosspaper.config.BaseIntegrationTest
import com.tosspaper.config.TestSecurityConfiguration
import com.tosspaper.models.jooq.Tables
import com.tosspaper.models.jooq.tables.records.TenderDocumentsRecord
import com.tosspaper.models.jooq.tables.records.TendersRecord
import org.jooq.DSLContext
import org.springframework.beans.factory.annotation.Autowired

import java.time.OffsetDateTime

class TenderDocumentRepositorySpec extends BaseIntegrationTest {

    @Autowired
    DSLContext dsl

    @Autowired
    TenderDocumentRepository tenderDocumentRepository

    Long companyId
    String companyIdStr
    String tenderId

    def setup() {
        companyId = TestSecurityConfiguration.TEST_COMPANY_ID
        companyIdStr = companyId.toString()

        dsl.insertInto(Tables.COMPANIES)
            .set(Tables.COMPANIES.ID, companyId)
            .set(Tables.COMPANIES.NAME, "Test Company")
            .set(Tables.COMPANIES.EMAIL, "test@test.com")
            .set(Tables.COMPANIES.ASSIGNED_EMAIL, "test@dev.test.com")
            .onDuplicateKeyIgnore()
            .execute()

        tenderId = UUID.randomUUID().toString()
        def tenderRecord = new TendersRecord()
        tenderRecord.setId(tenderId)
        tenderRecord.setCompanyId(companyIdStr)
        tenderRecord.setName("Test Tender " + tenderId)
        tenderRecord.setStatus("pending")
        tenderRecord.setCreatedBy("user-1")
        dsl.insertInto(Tables.TENDERS).set(tenderRecord).execute()
    }

    def cleanup() {
        dsl.deleteFrom(Tables.TENDER_DOCUMENTS).where(Tables.TENDER_DOCUMENTS.TENDER_ID.eq(tenderId)).execute()
        dsl.deleteFrom(Tables.TENDERS).where(Tables.TENDERS.ID.eq(tenderId)).execute()
    }

    // ==================== insert ====================

    def "should insert document with all fields and return record with generated timestamps"() {
        given: "a document record with all fields populated"
            def record = buildDocumentRecord(tenderId, companyIdStr, "contract.pdf")
            record.setErrorReason("some error")
            record.setUploadedAt(OffsetDateTime.now())

        when: "inserting the record"
            def inserted = tenderDocumentRepository.insert(record)

        then: "record is persisted with all fields"
            inserted != null
            inserted.id == record.id
            inserted.tenderId == tenderId
            inserted.companyId == companyIdStr
            inserted.fileName == "contract.pdf"
            inserted.contentType == "application/pdf"
            inserted.fileSize == 1024L
            inserted.s3Key == record.s3Key
            inserted.status == "ready"
            inserted.errorReason == "some error"
            inserted.uploadedAt != null

        and: "timestamps are auto-generated by the database"
            inserted.createdAt != null
            inserted.updatedAt != null
            inserted.deletedAt == null
    }

    def "should insert document with null optional fields (errorReason, metadata, uploadedAt)"() {
        given: "a minimal document record with no optional fields"
            def record = buildDocumentRecord(tenderId, companyIdStr, "minimal.pdf")

        when: "inserting the record"
            def inserted = tenderDocumentRepository.insert(record)

        then: "record is persisted with null optional fields"
            inserted != null
            inserted.id == record.id
            inserted.fileName == "minimal.pdf"
            inserted.errorReason == null
            inserted.metadata == null
            inserted.uploadedAt == null
            inserted.deletedAt == null

        and: "required timestamps are generated"
            inserted.createdAt != null
            inserted.updatedAt != null
    }

    // ==================== findById ====================

    def "should find document by id"() {
        given: "a document in the database"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "find-me.pdf"))

        when: "finding by id"
            def result = tenderDocumentRepository.findById(inserted.id)

        then: "the document is returned"
            result != null
            result.id == inserted.id
            result.fileName == "find-me.pdf"
            result.tenderId == tenderId
    }

    def "should return empty when document not found"() {
        when: "finding a nonexistent document"
            tenderDocumentRepository.findById("nonexistent-id")

        then: "NotFoundException is thrown"
            thrown(com.tosspaper.common.NotFoundException)
    }

    def "should return empty when document is soft-deleted"() {
        given: "a soft-deleted document"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "deleted.pdf"))
            tenderDocumentRepository.softDelete(inserted.id)

        when: "finding the deleted document by id"
            tenderDocumentRepository.findById(inserted.id)

        then: "NotFoundException is thrown"
            thrown(com.tosspaper.common.NotFoundException)
    }

    // ==================== findByTenderId ====================

    def "should return documents scoped to tender"() {
        given: "documents for this tender and another tender"
            def otherTenderId = UUID.randomUUID().toString()
            def otherTender = new TendersRecord()
            otherTender.setId(otherTenderId)
            otherTender.setCompanyId(companyIdStr)
            otherTender.setName("Other Tender")
            otherTender.setStatus("pending")
            otherTender.setCreatedBy("user-1")
            dsl.insertInto(Tables.TENDERS).set(otherTender).execute()

            tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "doc1.pdf"))
            tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "doc2.pdf"))
            tenderDocumentRepository.insert(buildDocumentRecord(otherTenderId, companyIdStr, "other-doc.pdf"))

        when: "listing documents for this tender"
            def results = tenderDocumentRepository.findByTenderId(tenderId, null, 20, null, null)

        then: "only documents for this tender are returned"
            results.size() == 2
            results.every { it.tenderId == tenderId }

        cleanup:
            dsl.deleteFrom(Tables.TENDER_DOCUMENTS).where(Tables.TENDER_DOCUMENTS.TENDER_ID.eq(otherTenderId)).execute()
            dsl.deleteFrom(Tables.TENDERS).where(Tables.TENDERS.ID.eq(otherTenderId)).execute()
    }

    def "should exclude soft-deleted documents"() {
        given: "an active and a soft-deleted document"
            def active = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "active.pdf"))
            def deleted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "deleted.pdf"))
            tenderDocumentRepository.softDelete(deleted.id)

        when: "listing documents"
            def results = tenderDocumentRepository.findByTenderId(tenderId, null, 20, null, null)

        then: "only the active document is returned"
            results.size() == 1
            results[0].fileName == "active.pdf"
    }

    def "should filter by status"() {
        given: "documents with different statuses"
            def readyDoc = buildDocumentRecord(tenderId, companyIdStr, "ready.pdf")
            readyDoc.setStatus("ready")
            tenderDocumentRepository.insert(readyDoc)

            def processingDoc = buildDocumentRecord(tenderId, companyIdStr, "processing.pdf")
            processingDoc.setStatus("processing")
            tenderDocumentRepository.insert(processingDoc)

        when: "filtering by status 'ready'"
            def results = tenderDocumentRepository.findByTenderId(tenderId, "ready", 20, null, null)

        then: "only ready documents are returned"
            results.size() == 1
            results[0].fileName == "ready.pdf"
            results[0].status == "ready"
    }

    def "should respect limit parameter (returns limit+1 for has_more detection)"() {
        given: "5 documents for the tender"
            5.times { i ->
                tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "doc${i}.pdf"))
            }

        when: "listing with limit 2 (repo fetches limit+1 internally)"
            def results = tenderDocumentRepository.findByTenderId(tenderId, null, 2, null, null)

        then: "returns limit+1 records for has_more detection"
            results.size() == 3
    }

    def "should order by created_at desc"() {
        given: "documents inserted in sequence with time gaps"
            def doc1 = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "first.pdf"))
            Thread.sleep(50)
            def doc2 = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "second.pdf"))
            Thread.sleep(50)
            def doc3 = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "third.pdf"))

        when: "listing documents"
            def results = tenderDocumentRepository.findByTenderId(tenderId, null, 20, null, null)

        then: "documents are returned newest first"
            results.size() == 3
            results[0].fileName == "third.pdf"
            results[1].fileName == "second.pdf"
            results[2].fileName == "first.pdf"
    }

    def "should support cursor pagination"() {
        given: "3 documents inserted in order"
            def doc1 = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "first.pdf"))
            Thread.sleep(50)
            def doc2 = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "second.pdf"))
            Thread.sleep(50)
            def doc3 = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "third.pdf"))

        and: "first page fetched with limit 1 (returns 2 due to limit+1)"
            def page1 = tenderDocumentRepository.findByTenderId(tenderId, null, 1, null, null)

        and: "cursor is the last record returned from page 1 (the newest document)"
            def cursorRecord = page1[0] // "third.pdf" is newest

        when: "fetching second page using cursor"
            def page2 = tenderDocumentRepository.findByTenderId(
                tenderId, null, 1,
                cursorRecord.createdAt, cursorRecord.id
            )

        then: "second page contains next records after cursor"
            page2[0].fileName == "second.pdf"
    }

    // ==================== softDelete ====================

    def "should soft-delete a document (returns 1)"() {
        given: "an existing document"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "to-delete.pdf"))

        when: "soft-deleting the document"
            def rowsUpdated = tenderDocumentRepository.softDelete(inserted.id)

        then: "1 row is updated"
            rowsUpdated == 1

        and: "the document's deleted_at is set in the database"
            def dbRecord = dsl.selectFrom(Tables.TENDER_DOCUMENTS)
                .where(Tables.TENDER_DOCUMENTS.ID.eq(inserted.id))
                .fetchSingle()
            dbRecord.deletedAt != null
    }

    def "should return 0 when document already soft-deleted"() {
        given: "an already soft-deleted document"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "already-deleted.pdf"))
            tenderDocumentRepository.softDelete(inserted.id)

        when: "soft-deleting again"
            def rowsUpdated = tenderDocumentRepository.softDelete(inserted.id)

        then: "0 rows updated because deleted_at is already set"
            rowsUpdated == 0
    }

    def "should return 0 when document not found"() {
        when: "soft-deleting a nonexistent document"
            def rowsUpdated = tenderDocumentRepository.softDelete("nonexistent-id")

        then: "0 rows updated"
            rowsUpdated == 0
    }

    // ==================== findByExternalTaskId ====================

    def "TC-TDR-FBET01: returns document when external_task_id matches"() {
        given: "a document with an external_task_id"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "task-doc.pdf"))
            def taskId = "reducto-task-" + UUID.randomUUID().toString()
            dsl.execute("UPDATE tender_documents SET external_task_id = ? WHERE id = ?", taskId, inserted.id)

        when: "looking up by external_task_id"
            def result = tenderDocumentRepository.findByExternalTaskId(taskId)

        then: "the document is found"
            result.isPresent()
            result.get().id == inserted.id
            result.get().fileName == "task-doc.pdf"
    }

    def "TC-TDR-FBET02: returns empty Optional when no document matches the external_task_id"() {
        when: "looking up an unknown task ID"
            def result = tenderDocumentRepository.findByExternalTaskId("unknown-task-xyz")

        then: "empty Optional is returned"
            result.isEmpty()
    }

    def "TC-TDR-FBET03: returns empty Optional for soft-deleted document with matching task_id"() {
        given: "a soft-deleted document with an external_task_id"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "deleted-task-doc.pdf"))
            def taskId = "reducto-task-deleted-" + UUID.randomUUID().toString()
            dsl.execute("UPDATE tender_documents SET external_task_id = ?, deleted_at = NOW() WHERE id = ?",
                    taskId, inserted.id)

        when: "looking up by task_id"
            def result = tenderDocumentRepository.findByExternalTaskId(taskId)

        then: "soft-deleted document is not returned"
            result.isEmpty()
    }

    // ==================== updateExternalFileId ====================

    def "TC-TDR-UEFI01: persists external_file_id and updates updated_at"() {
        given: "an existing document"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "file-id-doc.pdf"))
            def fileId = "reducto-file-" + UUID.randomUUID().toString()

        when: "updating the external_file_id"
            def rowsUpdated = tenderDocumentRepository.updateExternalFileId(inserted.id, fileId)

        then: "one row updated"
            rowsUpdated == 1

        and: "external_file_id is persisted in the database"
            def row = dsl.fetch("SELECT external_file_id FROM tender_documents WHERE id = ?", inserted.id)
            row[0].getValue("external_file_id") == fileId
    }

    def "TC-TDR-UEFI02: returns 0 when document id does not exist"() {
        when:
            def rowsUpdated = tenderDocumentRepository.updateExternalFileId("nonexistent-id", "any-file-id")

        then:
            rowsUpdated == 0
    }

    def "TC-TDR-UEFI03: returns 0 when document is soft-deleted"() {
        given: "a soft-deleted document"
            def inserted = tenderDocumentRepository.insert(buildDocumentRecord(tenderId, companyIdStr, "soft-deleted.pdf"))
            tenderDocumentRepository.softDelete(inserted.id)

        when: "attempting to update external_file_id on a deleted document"
            def rowsUpdated = tenderDocumentRepository.updateExternalFileId(inserted.id, "some-file-id")

        then: "0 rows updated — soft-deleted rows are excluded"
            rowsUpdated == 0
    }

    // ==================== Helper Methods ====================

    private TenderDocumentsRecord buildDocumentRecord(String tenderId, String companyId, String fileName) {
        def record = new TenderDocumentsRecord()
        record.setId(UUID.randomUUID().toString())
        record.setTenderId(tenderId)
        record.setCompanyId(companyId)
        record.setFileName(fileName)
        record.setContentType("application/pdf")
        record.setFileSize(1024L)
        record.setS3Key("tenders/${companyId}/${tenderId}/${record.getId()}/${fileName}")
        record.setStatus("ready")
        return record
    }
}
