package com.tosspaper.models.domain;

import com.tosspaper.models.enums.MessageDirection;
import com.tosspaper.models.enums.MessageStatus;
import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Represents an individual email message within a conversation thread.
 * Contains all email metadata, content, and tracking information for
 * both inbound and outbound messages.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EmailMessage {
    
    /** Unique identifier for this message, generated by the database */
    private UUID id;
    
    /** Reference to the thread this message belongs to */
    private UUID threadId;
    
    /** Company ID that owns this message */
    private Long companyId;
    
    /** Email provider that processed this message (e.g., "postmark", "sendgrid") */
    private String provider;
    
    /** Provider-specific message identifier used for correlation and idempotency */
    private String providerMessageId;
    
    /** Message ID this email is replying to, used for threading */
    private String inReplyTo;
    
    /** Email address of the sender */
    private String fromAddress;
    
    /** Primary recipient email addresses (comma-separated if multiple) */
    private String toAddress;
    
    /** Carbon copy recipient email addresses (comma-separated if multiple) */
    private String cc;
    
    /** Blind carbon copy recipient email addresses (comma-separated if multiple) */
    private String bcc;
    
    /** Subject line of the email */
    private String subject;
    
    /** Plain text content of the email body */
    private String bodyText;
    
    /** HTML content of the email body */
    private String bodyHtml;
    
    /** JSON string containing email headers for debugging and processing */
    private String headers;
    
    /** Direction of the message: incoming for received, outgoing for sent */
    private MessageDirection direction;
    
    /** Processing status: received, processed, failed */
    private MessageStatus status;
    
    /** Timestamp when the message was created by the provider in UTC */
    private OffsetDateTime providerTimestamp;
    
    /** Timestamp when this message was stored in our system in UTC */
    private OffsetDateTime createdAt;
    
    /** List of file attachments associated with this email message */
    private List<FileObject> attachments;

    private int attachmentsCount;
    
    /**
     * Check if this email message has any attachments.
     * 
     * @return true if there are attachments, false otherwise
     */
    public boolean hasAttachments() {
        return attachments != null && !attachments.isEmpty();
    }
}
