package com.tosspaper.models.domain;

import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Represents an email conversation thread that groups related messages together.
 * A thread is created when the first email in a conversation is received and
 * subsequent replies are added to the same thread.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EmailThread {
    
    /** Unique identifier for this thread, generated by the database */
    private UUID id;
    
    /** Subject line of the email thread, typically from the first message */
    private String subject;
    
    /** Email provider that originated this thread (e.g., "postmark", "sendgrid") */
    private String provider;
    
    /** Provider-specific thread identifier used for correlation and idempotency */
    private String providerThreadId;
    
    /** Total number of messages in this thread, updated as messages are added */
    private Integer messageCount;
    
    /** Timestamp when this thread was first created in UTC */
    private OffsetDateTime createdAt;
    
    /** Timestamp when this thread was last updated in UTC */
    private OffsetDateTime lastUpdatedAt;
    
    /** Timestamp when this thread was soft deleted (NULL = active) */
    private OffsetDateTime deletedAt;
}
