package com.tosspaper.models.domain;

import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;

/**
 * Represents a file attachment associated with an email message.
 * Contains metadata about the file including storage location, size,
 * and integrity verification information.
 */
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class EmailAttachment {
    
    /** Unique identifier for this attachment, generated by the database */
    private UUID id;
    
    /** Reference to the message this attachment belongs to */
    private UUID messageId;
    
    /** Assigned unique identifier for this attachment (providerMessageId_uuid) */
    private String assignedId;
    
    /** Original filename of the attachment as provided by the sender */
    private String fileName;
    
    /** MIME type of the attachment (e.g., "application/pdf", "image/jpeg") */
    private String contentType;
    
    /** Size of the attachment file in bytes */
    private Long sizeBytes;
    
    /** URL or path where the attachment file is stored (e.g., S3 URL) */
    private String storageUrl;
    
    /** Local file path where the file is stored in the filesystem */
    private String localFilePath;
    
    /** Hash checksum of the file content for integrity verification */
    private String checksum;
    
    /** Current upload status of the attachment */
    private AttachmentStatus status;
    
    /** Number of upload attempts made */
    private Integer attempts;
    
    /** AWS region where the file is stored (e.g., us-east-1, eu-west-1) */
    private String region;
    
    /** AWS endpoint where the file is stored (e.g., s3.amazonaws.com, s3.us-east-1.amazonaws.com) */
    private String endpoint;
    
    /** Additional metadata for the attachment (S3 tags, custom fields, etc.) */
    private Map<String, String> metadata;
    
    /** Timestamp when this attachment was last updated */
    private OffsetDateTime lastUpdatedAt;
    
    /** Timestamp when this attachment record was created in our system in UTC */
    private OffsetDateTime createdAt;
}
