/*
 * This source file was generated by the Gradle 'init' task
 */
package com.tosspaper.emailengine

import spock.lang.Specification

class ApiTossPaperApplicationTest extends Specification {
    def "application class exists"() {
        expect:
        // Simple test to verify the test application class exists
        TestApplication != null
    }
}
